spring:
  application:
    name: igris-application
  config:
    import: "configserver:"
  cloud:
    compatibility-verifier:
      enabled: false
    config:
      uri: http://localhost:8888
my:
  application-name: chidori-app-local

management:
  endpoints:
    web:
      exposure:
        include: health, info, env, loggers, metrics, refresh

db:
  name: chidori-db-local